## user lvms on SNO
## pvc will show pending (not bound) until creating the POD/Deployment that consumes it because storageClass lvms-vg1 is of type WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-log
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-cephfs
